// flow-typed signature: 75ac6df605886739287b1a0c5ee849d7
// flow-typed version: <<STUB>>/lorem-ipsum_v^2.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lorem-ipsum'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lorem-ipsum' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lorem-ipsum/dist/@types/nock-exec.d' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/bin/lorem-ipsum.bin' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/constants/cli' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/constants/commands' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/constants/errors' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/constants/formats' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/constants/lineEndings' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/constants/platforms' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/constants/regex' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/constants/words' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/index' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/lib/generator' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/lib/LoremIpsum' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/capitalize' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/copyToClipboard' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/getCopyCommand' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/getPlatform' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/getVersion' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/index' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/isNode' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/isReactNative' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/isSupportedPlatform' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/isWindows' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/makeArrayOfLength' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/dist/util/makeArrayOfStrings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lorem-ipsum/dist/@types/nock-exec.d.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/@types/nock-exec.d'>;
}
declare module 'lorem-ipsum/dist/bin/lorem-ipsum.bin.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/bin/lorem-ipsum.bin'>;
}
declare module 'lorem-ipsum/dist/constants/cli.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/constants/cli'>;
}
declare module 'lorem-ipsum/dist/constants/commands.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/constants/commands'>;
}
declare module 'lorem-ipsum/dist/constants/errors.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/constants/errors'>;
}
declare module 'lorem-ipsum/dist/constants/formats.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/constants/formats'>;
}
declare module 'lorem-ipsum/dist/constants/lineEndings.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/constants/lineEndings'>;
}
declare module 'lorem-ipsum/dist/constants/platforms.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/constants/platforms'>;
}
declare module 'lorem-ipsum/dist/constants/regex.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/constants/regex'>;
}
declare module 'lorem-ipsum/dist/constants/words.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/constants/words'>;
}
declare module 'lorem-ipsum/dist/index.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/index'>;
}
declare module 'lorem-ipsum/dist/lib/generator.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/lib/generator'>;
}
declare module 'lorem-ipsum/dist/lib/LoremIpsum.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/lib/LoremIpsum'>;
}
declare module 'lorem-ipsum/dist/util/capitalize.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/capitalize'>;
}
declare module 'lorem-ipsum/dist/util/copyToClipboard.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/copyToClipboard'>;
}
declare module 'lorem-ipsum/dist/util/getCopyCommand.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/getCopyCommand'>;
}
declare module 'lorem-ipsum/dist/util/getPlatform.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/getPlatform'>;
}
declare module 'lorem-ipsum/dist/util/getVersion.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/getVersion'>;
}
declare module 'lorem-ipsum/dist/util/index.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/index'>;
}
declare module 'lorem-ipsum/dist/util/isNode.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/isNode'>;
}
declare module 'lorem-ipsum/dist/util/isReactNative.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/isReactNative'>;
}
declare module 'lorem-ipsum/dist/util/isSupportedPlatform.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/isSupportedPlatform'>;
}
declare module 'lorem-ipsum/dist/util/isWindows.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/isWindows'>;
}
declare module 'lorem-ipsum/dist/util/makeArrayOfLength.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/makeArrayOfLength'>;
}
declare module 'lorem-ipsum/dist/util/makeArrayOfStrings.js' {
  declare module.exports: $Exports<'lorem-ipsum/dist/util/makeArrayOfStrings'>;
}
