// @flow
import loremIpsum from 'lorem-ipsum'
import type {Article} from '../entities'

const demoArticle:Article = {
  active: true,
  pseudoPriceSingle: 0,
  articleId: '0',
  articleUrl: '',
  articleContainerUrl: '',
  attributes: [],
  bundleSkus: [],
  closeout: false,
  containerSku: '',
  customizableUrl: null,
  customTailorSetId: null,
  deliveryDate: '',
  filterValues: { color: null, size: null, variant: null, style: null },
  hasPriceRules: false,
  images: ['data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='],
  isCustomTailor: false,
  isNew: false,
  isDummy: true,
  longDescription: loremIpsum({counts: 20}),
  masterArticleNumber: '',
  ordernumber: '10071666',
  packUnit: 'Packung',
  packUnitId: null,
  price: 10.00,
  priceRules: [],
  priceSingle: 10.00,
  productNumber: '123456',
  pseudoPrice: 0,
  purchaseUnit: 1,
  rating: { value: 5, count: 200 },
  crossSellSkus: [],
  requestSamplesUrl: null,
  relatedSkus: [],
  sale: false,
  series: { name: null, url: null },
  seriesSkus: [],
  serviceIcons: [],
  shippingFree: false,
  shortDescription: loremIpsum({count: 3}),
  similarSkus: [],
  stock: 10,
  subtitle: loremIpsum({count: 1}),
  tax: 0.19,
  title: loremIpsum({count: 3, units: 'words'}),
  unitName: 'Stück',
  votes: []
}

export default demoArticle